### ISSUE TITLE
use timestamp as parameter?

### ISSUE THREAD

**Issue by rolandow** [etsy/statsd#279]
Is is possible to add a timestamp as parameter?

I am currently working on a script that processes e-mail bounce statuses. This script runs every half hour, but I do have the timestamps of the reception of the bounce station. I'd like to use this timestamp for my metrics, because this will give a better view of what happens when.

So is it possible to send the timestamps (which are probably in the past) as well?

**Comment by vv80** [comment]
In my opinion, there is another important use case where this feature is needed. I want to contact several webservices and download a huge XML file of metrics and their generation timestamp from each one. Some servers cache the metrics they generate for a certain period and other throttle down the download speed, so it might take a minute to download the whole file. For these reasons I am not interested in the timestamp when the download finished, but rather in the timestamp that comes in the XML payload. And I want to use statsd because of the UDP protocol.
What makes adding this feature so difficult ? I do not know how the program is structured but what is needed is just to parse another input parameter and send with the other data for gauge metrics.

**Comment by cyberrodent** [comment]
You may want to take a look at https://github.com/etsy/logster which can be used to parse log files and send metrics to graphite, using the timestamp from the log file.
