### ISSUE TITLE
Ability to blacklist some metrics

### ISSUE THREAD

**Issue by jantman** [etsy/statsd#293]
One or two poorly chosen metrics suddenly pushed to statsd and graphite can wreak havoc on the system. I had this experience today with a metric in a Django app that ended up including a URL portion in the metric name, and quickly generated 500k unique metrics.

I'd love the ability to specify a file of blacklisted metric names that statsd will simply ignore (or maybe increment a blacklist_metric counter and do nothing else). Ideally in my view, it should be either regex matching (if this is performant enough) or match metric names that start with one of the strings in the file. Statsd should also stop pushing values for these metrics to backends, even if deleteIdleStats or delete<type> is false.

Finally, an admin TCP interface command to reload the blacklist, so it can be applied to a running statsd instance.

**Comment by mrtazz** [comment]
closing this since I don't think this should be a feature. If you don't want specifics metrics, it should be able to stop sending them. And I also don't think network IO will become a problem before statsd can't keep up with sending data. So the graphite solution could be some sort of last resort for this.

**Comment by jantman** [comment]
For the record, in hindsight, I agree with closing this issue. Sorry for leaving it open all this time.
