### ISSUE TITLE
Is it possible to run StatsD in a highly-available setup?

### ISSUE THREAD

**Issue by rfkrocktk** [etsy/statsd#552]
In this modern age of "the cloud™" and cheap automated VMs, it's really wise to make most if not all of your infrastructure highly available. 

Is there a way to run statsd in a highly-available setup where data is replicated between two instances behind a load-balancer like HAProxy? We'd like to ensure that statsd is _always_ running and that we can do maintenance without breaking things.

**Comment by pathzzrd** [comment]
@rfkrocktk Using HAProxy to proxy UDP, one could run two statsd instances and failover should one disappear. statsd supports health checks over it's TCP admin port which could be used for an automatic failover scenario should a health check timeout or return a bad status.

As for replication, currently there is no way to replicate data bidirectionally between statsd instances without creating duplicate metrics. However it should be noted that all of statsd's data resides in memory and, if run with the "deleteIdleStats" config option, that on a backend flush* all metric data is cleared from memory. Assuming your backend data sink is graphite, on automatic failover there might be a small blip in graphs. This would depend on when the failover occurred and would be most noticeable if the failover occurred in the middle to end of a bucket*. The original statsd instance will have consumed greater than half of that bucket's metrics, leaving the failover instance with less information to aggregate over.

That said, another route that could be taken is teeing UDP traffic to 2 statsd instances using HAProxy and then using another HAProxy, to select the backend flush output from only one of the instances to forward on to your data storage layer. Both statsd instances would have the same in memory data and your failover scenario would select which statsd instance to receive aggregated metrics from. Since statsd defaults to using a UDP protocol nothing ill should happen should HAProxy not be able to talk to one of the statsd instances.

Hope this helps!

*See: https://github.com/etsy/statsd#key-concepts
