### ISSUE TITLE
multi statsd overwrite metrics

### ISSUE THREAD

**Issue by billowqiu** [etsy/statsd#580]
I have two statsd instance. These two statsd send the same counter metrics("login.qps") to one graphite.
Then i found graphite have lost one counter.

**Comment by billowqiu** [comment]
for example:
A app send metrics to A statsd use 10 count per second
B app send metrics to B statsd use 20 count per second
my expect value is (10*60 + 20*60) = 1800 qps
if i use statsd defalut config, graphite show 200 qps.
if i set "flushInterval" to 60000(1min), graphite show 1200 qps

**Comment by pathzzrd** [comment]
statsd is not architectured to handled the use case of running multiple daemons to aggregate the same metric space when using the graphite backend. This is because Graphite will overwrite any metrics that it receives that have the same metric name and timestamp, it does not aggregate (sum, avg, etc) them on ingestion. This is why you only see one of the 2 values being sent. 

My suggestion is to namespace the metrics based on the application, for example "A.login.qps" and "B.login.qps". You can combine these two metrics together in one graphite graph if you need totals. 

As for your second inquiry, graphite needs to be configured with the knowledge of the flushinterval of the upstream statsd server. You can configure graphite to receive the data based on the flush interval of your applications by setting the initial resolution in the [storage schemas config](http://graphite.readthedocs.io/en/latest/config-carbon.html#storage-schemas-conf) to the same as your statsd flushinterval. This can be done per application as the setting takes a regex based on the metric name.

here is an example of the config for the default statsd flushrate (10s)
```
[stats]
priority = 0
pattern = ^stats\..*
retentions = 10s:1d,1m:7d,10m:5y 
```

hope this helps!

**Comment by billowqiu** [comment]
Thanks for your reply!
I understand the use case of statsd.
