### ISSUE TITLE
Produce duplicate files when using counter

### ISSUE THREAD

**Issue by chengweichao** [etsy/statsd#582]
Hi, I encountered a problem when using statsd + graphite. When I run below command, it creates two same-sized file. I'm not sure if I have the wrong setting? Any suggestion will be appreciated.

command:
echo "foo:1|c" | nc -w 1 -u 127.0.0.1 8125

two same-sized file
/opt/graphite/storage/whisper/stats/foo.wsp
/opt/graphite/storage/whisper/stats_counts/foo.wsp

**Comment by pathzzrd** [comment]
hi @chengweichao 

The file under stats_counts is a raw counter and given it should have a data point with the value 1 in it.
the file under stats is a rate and (depending on your statsd flushInterval and graphite retention settings) will have a per second rate. 

with the default flushInterval of 10s (and if you only sent 1 packet with "foo:1|c") the stats.foo datapoint in graphite would be 1foo/10s or "0.1"

the files are the same size because graphite stores the data in whisper files which like the RRD format are pre-allocated for the entirety of the retention periods set in [storage-schemas.conf](http://graphite.readthedocs.io/en/latest/config-carbon.html#storage-schemas-conf)

**Comment by chengweichao** [comment]
Hi @pathzzrd

Thanks for your reply, very detailed.
